version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: bookswakeus
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
#    expose:
#      - '5432'
  dbclient:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.lt
      PGADMIN_DEFAULT_PASSWORD: p
    ports:
      - "8888:80"
